/*
 * BlipComposerPanel.java
 *
 * Created on November 24, 2007, 10:45 PM
 */

package com.meapsoft.gui.composers;

import com.meapsoft.composers.BlipComposer;
import com.meapsoft.composers.Composer;


/**
 *
 * @author  Mike
 */
public class BlipComposerPanel extends ComposerSettingsPanel
{
    /** Creates new form BlipComposerPanel */
    public BlipComposerPanel()
    {
        initComponents();
    }
    
    public int initComposer()
    {
		mComposer = new BlipComposer(mParentTab.featFile, mParentTab.edlFile,
                        jCheckBox1.isSelected());
        ((BlipComposer)mComposer).setBlipWav(mParentTab.dataDirectory + mParentTab.slash + "blip.wav");
    
        return 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();

        jCheckBox1.setText("silent mode");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jCheckBox1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jCheckBox1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


	public int run() 
	{
		return 0;
	}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
    
}
